# This file was generated by tools/update/update.py

include rauc-hawkbit-updater.inc

# Version 1.4 released 2025-07-14T13:27:11Z.
SRC_URI += "https://github.com/rauc/rauc-hawkbit-updater/releases/download/v1.4/rauc-hawkbit-updater-1.4.tar.xz"
SRC_URI[sha256sum] = "635da0807699d2efef63e44f6f6563efdb88f2f826f8ad7f8f852473a5416d71"
