# This file was generated by tools/update/update.py

DESCRIPTION = "device-tree and barebox-related tools"
HOMEPAGE = "http://git.pengutronix.de/?p=tools/dt-utils.git"
SECTION = "base"
LICENSE = "GPL-2.0-only"
LIC_FILES_CHKSUM = "file://COPYING;md5=18d902a0242c37a4604224b47d02f802"
DEPENDS = "udev"

SRC_URI = "git://git.pengutronix.de/git/tools/dt-utils;protocol=https;branch=${SRCBRANCH}"

# Git tag v2023.11.0 pointing at a commit from 2023-11-24 11:48:33 +0100
SRCBRANCH = "master"
SRCREV = "848841cd9459e85c8419ddca567fb4e49bbf711c"

inherit autotools pkgconfig gettext

NOAUTOPACKAGEDEBUG = "1"

FILES:${PN}-dbg = "${libdir}/.debug/"

PACKAGES =+ "${PN}-barebox-state ${PN}-barebox-state-dbg"
FILES:${PN}-barebox-state = "${bindir}/barebox-state"
FILES:${PN}-barebox-state-dbg = "${bindir}/.debug/barebox-state"

PACKAGES =+ "${PN}-fdtdump ${PN}-fdtdump-dbg"
FILES:${PN}-fdtdump = "${bindir}/fdtdump"
FILES:${PN}-fdtdump-dbg = "${bindir}/.debug/fdtdump"

PACKAGES =+ "${PN}-dtblint ${PN}-dtblint-dbg"
FILES:${PN}-dtblint = "${bindir}/dtblint"
FILES:${PN}-dtblint-dbg = "${bindir}/.debug/dtblint"
