# This file was generated by tools/update/update.py

LICENSE = "LGPL-2.1-or-later"
LIC_FILES_CHKSUM = " \
    file://COPYING;md5=4fbd65380cdd255951079008b364516c \
    file://README.rst;beginline=114;endline=132;md5=a569a9868bb81fb591cf2cdfdf61db1d \
    "

SUMMARY = "hawkBit client for RAUC"

DEPENDS = "python3-setuptools-scm-native"

SRC_URI = " \
    git://github.com/rauc/rauc-hawkbit.git;protocol=https;branch=${SRCBRANCH} \
    file://rauc-hawkbit.service \
"

# Version v0.2.0-1-g0934383 commited 2021-03-30 14:53:37 +0200
PV = "0.2.0+git"
SRCBRANCH = "master"
SRCREV = "093438304f0f57fe6b9fe12dc51c323f0ab8ca31"

inherit setuptools3 systemd

PACKAGES =+ "${PN}-service"
SYSTEMD_SERVICE:${PN}-service = "rauc-hawkbit.service"
SYSTEMD_PACKAGES = "${PN}-service"

do_install:append() {
    install -d ${D}${sysconfdir}/${BPN}/
    install -m 0644 ${S}/rauc_hawkbit/config.cfg ${D}${sysconfdir}/${BPN}/config.cfg
    install -d ${D}${systemd_unitdir}/system/
    install -m 0644 ${UNPACKDIR}/rauc-hawkbit.service ${D}${systemd_unitdir}/system/
    sed -i -e 's!@BINDIR@!${bindir}!g' -e 's!@SYSCONFDIR@!${sysconfdir}!g' \
    ${D}${systemd_unitdir}/system/rauc-hawkbit.service
}

RDEPENDS:${PN} += "python3-aiohttp python3-gbulb"
FILES:${PN}-service = " \
    ${bindir}/rauc-hawkbit-client \
    ${sysconfdir}/${BPN}/config.cfg \
    ${systemd_unitdir}/system/rauc-hawkbit.service \
"
