# This file was generated by tools/update/update.py

SUMMARY = "Content-Addressable Data Synchronization Tool"
HOMEPAGE = "https://github.com/systemd/casync"
LICENSE = "LGPL-2.1-or-later"
LIC_FILES_CHKSUM = "file://LICENSE.LGPL2.1;md5=4fbd65380cdd255951079008b364516c"

DEPENDS = "xz curl openssl acl zstd"

# Version v2-269-gb4b7e56 commited 2025-09-22 14:02:05 +0200
PV = "2+git"
SRCBRANCH = "main"
SRCREV = "b4b7e5606f785572b78a43626a27a45fe3df2fbd"

SRC_URI = "git://github.com/systemd/casync.git;protocol=https;branch=${SRCBRANCH}"

inherit meson pkgconfig

EXTRA_OEMESON += "-Dselinux=false -Dman=false -Dudevrulesdir=${nonarch_base_libdir}/udev/rules.d/"

BBCLASSEXTEND = "native nativesdk"

PACKAGECONFIG:class-native = ""
PACKAGECONFIG:class-nativesdk = ""
PACKAGECONFIG ?= "fuse udev"

PACKAGECONFIG[fuse] = "-Dfuse=true,-Dfuse=false,fuse"
PACKAGECONFIG[udev] = "-Dudev=true,-Dudev=false,udev"

FILES:${PN} += "${datadir}/bash-completion"
