# This file was generated by tools/update/update.py

SUMMARY = "GLib implementation of PEP 3156"
HOMEPAGE = "http://github.com/beeware/gbulb"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=edfe3d91d4b439ac8a8c23cebbf00501"

# Version 0.6.6 released 2024-09-13T02:59:12.
SRC_URI[sha256sum] = "b66bb1637e956a605636ac2820747583983715a87742beaddeb2e41da37b5154"

# python3-misc is needed for the signal module
RDEPENDS:${PN} = "python3-pygobject python3-asyncio python3-misc"

inherit pypi setuptools3
